### ISSUE TITLE
UnsatisfiedLinkError under 64-bit Java on Windows

### ISSUE THREAD

**Issue by ahitrin** [nauphone/ServerAccess#62]
We've got following exception:
```
C:\Program Files (x86)\Naumen\ServerAccess>"C:\Program Files\Java\jdk1.8.0_60\bi
n\java.exe" -classpath "ServerAccess-all.jar;C:\Program Files (x86)\NAUMEN\Serve
rAccess" ru.naumen.servacc.ui.Main
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SW
T libraries on 64-bit JVM
       at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
       at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
       at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
       at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
       at ru.naumen.servacc.ui.Main.run(Main.java:45)
       at ru.naumen.servacc.ui.Main.main(Main.java:36)
```

Known workaround: use 32-bit Java to run SA.

**Comment by ahitrin** [comment]
Probably, this bug was appeared after #55

**Comment by ahitrin** [comment]
To fix this issue we need to carefully set relations between desired build artifacts and sources they use. Currently, we build (using "shadow" plugin) single `ServerAccess-all.jar` file which contains only 32-bit `swt.jar`. Splitting must cause shadow plugin to be invoked at least 2 separate times, for the 32 bit arch and for 64 bit one.

**Comment by ahitrin** [comment]
Fixed in `master`.
